service: aws-node-project
frameworkVersion: '3'

custom:
  secrets: ${file(secrets.json)}
  tableName: "users-table"

provider:
  name: aws
  runtime: nodejs20.x
  region: 'ap-southeast-1'
  environment:
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    AWS_ID: ${self:custom.secrets.AWS_ID}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
      Resource: "arn:aws:dynamodb:ap-southeast-1:${self:custom.secrets.AWS_ID}:table/${self:custom.tableName}"

functions:
  verify-token:
    handler: functions/authorize.handler

  me:
    handler: functions/me.handler
    memorySize: 256
    timeout: 30
    events:
      - http:
          method: GET
          path: /me
          cors: true
          authorizer:
            name: verify-token
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 3600

  login:
    handler: functions/login.handler
    events:
      - http:
          method: POST
          path: /login
          cors: true

  register:
    handler: functions/register.handler
    events:
      - http:
          method: POST
          path: /register
          cors: true

  logout:
    handler: functions/logout.handler
    events:
      - http:
          method: POST
          path: /logout
          cors: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: pkey
            AttributeType: S
          - AttributeName: skey
            AttributeType: S
        KeySchema:
          - AttributeName: pkey
            KeyType: HASH
          - AttributeName: skey
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1